#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

// Composer
require(__DIR__ . '/vendor/autoload.php');

// Environment
require(__DIR__ . '/common/env.php');

// Yii
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

// Bootstrap application
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.global.php'),
    require(__DIR__ . '/common/config/main.local.php'),
    require(__DIR__ . '/console/config/main.global.php'),
    require(__DIR__ . '/console/config/main.local.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);

